---
namespace: homelaba
name: lxc
version: 0.1.0
readme: README.md
authors:
  - Artur Akmalov <artur@akmalov.com>
description: For prepare lxc homelab
license:
  - MIT
tags:
  - lxc
  - proxmox
  - tools
  - docker
repository: https://github.com/homelaba/ansible-role-homelab.git
documentation: https://github.com/homelaba/ansible-role-homelab.git
homepage: https://github.com/homelaba/ansible-role-homelab.git
issues: https://github.com/homelaba/ansible-role-homelab.git/issues